name: Cfg golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
permissions:
  contents: read
jobs:
  golangci:
    name: cfg
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
      - uses: actions/checkout@v2
      - run: go mod tidy
      - run: go mod vendor
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
